# Generated by Django 4.0.1 on 2022-01-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_tasktype_remove_task_type_task_type_tasktype_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='type_new',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='issue_tracker.Type'),
        ),
        migrations.AddField(
            model_name='task',
            name='type_old',
            field=models.ManyToManyField(blank=True, related_name='tasks_old', through='issue_tracker.TaskType', to='issue_tracker.Type'),
        ),
    ]
