# Generated by Django 4.0.1 on 2022-01-24 14:25

from django.db import migrations


def transfer_type(apps, schema_editor):
    Task = apps.get_model('issue_tracker.Task')
    for task in Task.objects.all():
        task.type_new.set(task.type_old.all())


def rollback_type(apps, schema_editor):
    Task = apps.get_model('issue_tracker.Task')
    for task in Task.objects.all():
        task.type_old.set(task.type_new.all())


class Migration(migrations.Migration):
    dependencies = [
        ('issue_tracker', '0003_remove_task_type_task_type_new_task_type_old'),
    ]

    operations = [
        migrations.RunPython(transfer_type, rollback_type)
    ]
