# Generated by Django 4.0.1 on 2022-01-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_auto_20220124_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type_new',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type_old',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
