# Generated by Django 4.0.1 on 2022-01-27 15:19

from django.db import migrations, models
import issue_tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0006_alter_type_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=50, validators=[issue_tracker.validators.MinLengthValidator(5)]),
        ),
    ]
