# Generated by Django 4.0.1 on 2022-01-27 16:01

from django.db import migrations, models
import issue_tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0007_alter_task_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=50, validators=[issue_tracker.validators.MinLengthValidator(5), issue_tracker.validators.is_alpha]),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(related_name='tasks', to='issue_tracker.Type'),
        ),
    ]
