# Generated by Django 4.0.1 on 2022-02-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0007_alter_task_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(related_name='tasks', to='issue_tracker.Type'),
        ),
    ]
